---
apiVersion: v1
kind: Service
metadata:
  name: soarcast-backend
  namespace: soarcast
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: workstation-shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workstation-shell
  namespace: workstation
  labels:
    app: workstation-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workstation-shell
  template:
    metadata:
      labels:
        app: workstation-shell
    spec:
      containers:
        - name: workstation-shell
          image: registry.gitlab.com/seth-projects/soarcast/backend:latest
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
